FROM cgr.dev/chainguard/wolfi-base:<%= ENV.fetch('TAG') %>

COPY apk-install /usr/sbin/

RUN apk add bash bats

RUN apk upgrade --update && rm -rf /var/cache/apk/*
ONBUILD RUN apk upgrade --update && rm -rf /var/cache/apk/*
