FROM cgr.dev/chainguard/wolfi-base:<%= ENV.fetch('TAG') %>

COPY apk-install /usr/sbin/

RUN apk-install bash git\
    && git clone https://github.com/bats-core/bats-core.git \
    && cd bats-core \
    && ./install.sh /usr/local \
    && cd .. \ 
    && rm -rf bats-core

RUN apk upgrade --update && rm -rf /var/cache/apk/*
ONBUILD RUN apk upgrade --update && rm -rf /var/cache/apk/*
