name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
      branches: 
      - "*"

jobs:
  build:
    strategy:
      matrix:
        version: ['3.2', '3.3', '3.4', '3.5', '3.6','3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.15', '3.16', '3.17' ,'3.18','latest']
    runs-on: ubuntu-latest
    env:
      REPOSITORY: alpine

    steps:

    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          aptible/${{ env.REPOSITORY }}
          quay.io/aptible/${{ env.REPOSITORY }}
        flavor: |
          latest=false
        tags: |
          type=schedule
          type=ref,event=branch,suffix=${{ format('-{0}', matrix.version) }}
          type=ref,event=tag,suffix=${{ format('-{0}', matrix.version) }}
          type=ref,event=pr,suffix=${{ format('-{0}', matrix.version) }}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: |
          "TAG=${{ matrix.version == 'latest' && '3.18' || matrix.version }}"
        file: ./Dockerfile
        push: false
        target: ${{ steps.metadata.outputs.images }}
        tags: ${{ steps.metadata.outputs.tags }}